update

diff --git a/.github/workflows/build-electron-app.yml b/.github/workflows/build-electron-app.yml
--- a/.github/workflows/build-electron-app.yml
+++ b/.github/workflows/build-electron-app.yml
@@ -2,8 +2,6 @@ name: "Nidum.ai macOS Build and Release"
 
 on:
   push:
-    branches:
-      - main
     tags:
       - 'v*'
 
@@ -11,7 +9,7 @@ jobs:
   create-release:
     runs-on: macos-latest
     permissions:
-      contents: write
+      contents: write  # Ensure the token has write permissions to contents
 
     steps:
       - uses: actions/checkout@v3
@@ -36,9 +34,19 @@ jobs:
           echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
         shell: bash
 
+      - name: Check GitHub Token Validity
+        id: check_token
+        run: |
+          TOKEN_VALID=$(curl -o /dev/null -s -w "%{http_code}\n" -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository }})
+          if [ "$TOKEN_VALID" -ne 200 ]; then
+            echo "Invalid GitHub Token or insufficient permissions."
+            exit 1
+          fi
+
       - name: Build Electron App
+        if: steps.check_token.outputs.TOKEN_VALID == '200'
         env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure this is correctly referenced
           APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
           APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
           APPLE_ID: ${{ secrets.APPLE_ID }}
@@ -72,7 +80,7 @@ jobs:
           xcrun stapler staple "$DMG_PATH"
 
       - name: Check Release
-        if: startsWith(github.ref, 'refs/tags/')
+        if: steps.check_token.outputs.TOKEN_VALID == '200' && startsWith(github.ref, 'refs/tags/')
         id: check_release
         run: |
           RELEASE_ID=$(curl -sL -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
@@ -83,7 +91,7 @@ jobs:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
 
       - name: Update Release
-        if: startsWith(github.ref, 'refs/tags/') && steps.check_release.outputs.RELEASE_ID != 'null'
+        if: steps.check_token.outputs.TOKEN_VALID == '200' && startsWith(github.ref, 'refs/tags/') && steps.check_release.outputs.RELEASE_ID != 'null'
         uses: actions/upload-release-asset@v1
         env:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
@@ -94,7 +102,7 @@ jobs:
           asset_content_type: application/x-apple-diskimage
 
       - name: Create Release
-        if: startsWith(github.ref, 'refs/tags/') && steps.check_release.outputs.RELEASE_ID == 'null'
+        if: steps.check_token.outputs.TOKEN_VALID == '200' && startsWith(github.ref, 'refs/tags/') && steps.check_release.outputs.RELEASE_ID == 'null'
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ env.DMG_PATH }}
